# POST http://localhost:3001/login HTTP/1.1
# content-type: application/json
# {
#     "username":"aa",
#     "password":"111"
# }

# GET http://localhost:3001/users HTTP/1.1

POST http://localhost:3001/login HTTP/1.1
content-type: application/json

{
    "username":"aa",
    "password":"111"
}